/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as veraGigEscrowSol from "./VeraGigEscrow.sol";
export type { veraGigEscrowSol };
import type * as veraGigLendingPoolSol from "./VeraGigLendingPool.sol";
export type { veraGigLendingPoolSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { VeraGigFeeRouter } from "./VeraGigFeeRouter";
export type { VeraScoreRegistry } from "./VeraScoreRegistry";
