/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VeraScoreRegistry {
  export type WorkerScoreStruct = {
    score: BigNumberish;
    lastUpdatedBlock: BigNumberish;
    tasksCompleted: BigNumberish;
    tasksAccepted: BigNumberish;
    disputesLost: BigNumberish;
    loansRepaidOnTime: BigNumberish;
    ubiClaimStreakDays: BigNumberish;
    earningConsistencyWeeks: BigNumberish;
  };

  export type WorkerScoreStructOutput = [
    score: bigint,
    lastUpdatedBlock: bigint,
    tasksCompleted: bigint,
    tasksAccepted: bigint,
    disputesLost: bigint,
    loansRepaidOnTime: bigint,
    ubiClaimStreakDays: bigint,
    earningConsistencyWeeks: bigint
  ] & {
    score: bigint;
    lastUpdatedBlock: bigint;
    tasksCompleted: bigint;
    tasksAccepted: bigint;
    disputesLost: bigint;
    loansRepaidOnTime: bigint;
    ubiClaimStreakDays: bigint;
    earningConsistencyWeeks: bigint;
  };
}

export interface VeraScoreRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedUpdaters"
      | "getFullProfile"
      | "getLoanTier"
      | "getScore"
      | "owner"
      | "renounceOwnership"
      | "scores"
      | "setAuthorizedUpdater"
      | "transferOwnership"
      | "updateScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ScoreUpdated"
      | "UpdaterAuthorized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedUpdaters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFullProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanTier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "scores", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedUpdater",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateScore",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedUpdaters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFullProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLoanTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getScore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scores", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedUpdater",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateScore",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreUpdatedEvent {
  export type InputTuple = [
    worker: AddressLike,
    oldScore: BigNumberish,
    newScore: BigNumberish,
    trigger: string
  ];
  export type OutputTuple = [
    worker: string,
    oldScore: bigint,
    newScore: bigint,
    trigger: string
  ];
  export interface OutputObject {
    worker: string;
    oldScore: bigint;
    newScore: bigint;
    trigger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdaterAuthorizedEvent {
  export type InputTuple = [updater: AddressLike, authorized: boolean];
  export type OutputTuple = [updater: string, authorized: boolean];
  export interface OutputObject {
    updater: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VeraScoreRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): VeraScoreRegistry;
  waitForDeployment(): Promise<this>;

  interface: VeraScoreRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedUpdaters: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getFullProfile: TypedContractMethod<
    [worker: AddressLike],
    [VeraScoreRegistry.WorkerScoreStructOutput],
    "view"
  >;

  getLoanTier: TypedContractMethod<[worker: AddressLike], [string], "view">;

  getScore: TypedContractMethod<[worker: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  scores: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        score: bigint;
        lastUpdatedBlock: bigint;
        tasksCompleted: bigint;
        tasksAccepted: bigint;
        disputesLost: bigint;
        loansRepaidOnTime: bigint;
        ubiClaimStreakDays: bigint;
        earningConsistencyWeeks: bigint;
      }
    ],
    "view"
  >;

  setAuthorizedUpdater: TypedContractMethod<
    [updater: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateScore: TypedContractMethod<
    [
      worker: AddressLike,
      newScore: BigNumberish,
      tasksCompleted: BigNumberish,
      tasksAccepted: BigNumberish,
      disputesLost: BigNumberish,
      loansRepaidOnTime: BigNumberish,
      ubiClaimStreakDays: BigNumberish,
      earningConsistencyWeeks: BigNumberish,
      trigger: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedUpdaters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getFullProfile"
  ): TypedContractMethod<
    [worker: AddressLike],
    [VeraScoreRegistry.WorkerScoreStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLoanTier"
  ): TypedContractMethod<[worker: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getScore"
  ): TypedContractMethod<[worker: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scores"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        score: bigint;
        lastUpdatedBlock: bigint;
        tasksCompleted: bigint;
        tasksAccepted: bigint;
        disputesLost: bigint;
        loansRepaidOnTime: bigint;
        ubiClaimStreakDays: bigint;
        earningConsistencyWeeks: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAuthorizedUpdater"
  ): TypedContractMethod<
    [updater: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateScore"
  ): TypedContractMethod<
    [
      worker: AddressLike,
      newScore: BigNumberish,
      tasksCompleted: BigNumberish,
      tasksAccepted: BigNumberish,
      disputesLost: BigNumberish,
      loansRepaidOnTime: BigNumberish,
      ubiClaimStreakDays: BigNumberish,
      earningConsistencyWeeks: BigNumberish,
      trigger: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ScoreUpdated"
  ): TypedContractEvent<
    ScoreUpdatedEvent.InputTuple,
    ScoreUpdatedEvent.OutputTuple,
    ScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UpdaterAuthorized"
  ): TypedContractEvent<
    UpdaterAuthorizedEvent.InputTuple,
    UpdaterAuthorizedEvent.OutputTuple,
    UpdaterAuthorizedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ScoreUpdated(address,uint16,uint16,string)": TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
    ScoreUpdated: TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;

    "UpdaterAuthorized(address,bool)": TypedContractEvent<
      UpdaterAuthorizedEvent.InputTuple,
      UpdaterAuthorizedEvent.OutputTuple,
      UpdaterAuthorizedEvent.OutputObject
    >;
    UpdaterAuthorized: TypedContractEvent<
      UpdaterAuthorizedEvent.InputTuple,
      UpdaterAuthorizedEvent.OutputTuple,
      UpdaterAuthorizedEvent.OutputObject
    >;
  };
}
