/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface VeraGigFeeRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOM"
      | "FEE_BPS"
      | "TREASURY_PCT"
      | "UBI_POOL_PCT"
      | "authorizedCallers"
      | "owner"
      | "renounceOwnership"
      | "routeFee"
      | "setAddresses"
      | "setAuthorizedCaller"
      | "transferOwnership"
      | "treasury"
      | "ubiPool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FeeRouted" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BPS_DENOM", values?: undefined): string;
  encodeFunctionData(functionFragment: "FEE_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TREASURY_PCT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UBI_POOL_PCT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "routeFee",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddresses",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedCaller",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "ubiPool", values?: undefined): string;

  decodeFunctionResult(functionFragment: "BPS_DENOM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "FEE_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_PCT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UBI_POOL_PCT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "routeFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ubiPool", data: BytesLike): Result;
}

export namespace FeeRoutedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    token: AddressLike,
    settlementAmount: BigNumberish,
    ubiContribution: BigNumberish,
    treasuryContribution: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    token: string,
    settlementAmount: bigint,
    ubiContribution: bigint,
    treasuryContribution: bigint
  ];
  export interface OutputObject {
    taskId: string;
    token: string;
    settlementAmount: bigint;
    ubiContribution: bigint;
    treasuryContribution: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VeraGigFeeRouter extends BaseContract {
  connect(runner?: ContractRunner | null): VeraGigFeeRouter;
  waitForDeployment(): Promise<this>;

  interface: VeraGigFeeRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOM: TypedContractMethod<[], [bigint], "view">;

  FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  TREASURY_PCT: TypedContractMethod<[], [bigint], "view">;

  UBI_POOL_PCT: TypedContractMethod<[], [bigint], "view">;

  authorizedCallers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  routeFee: TypedContractMethod<
    [taskId: BytesLike, token: AddressLike, settlementAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAddresses: TypedContractMethod<
    [_ubiPool: AddressLike, _treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setAuthorizedCaller: TypedContractMethod<
    [caller: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  ubiPool: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TREASURY_PCT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UBI_POOL_PCT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorizedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "routeFee"
  ): TypedContractMethod<
    [taskId: BytesLike, token: AddressLike, settlementAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAddresses"
  ): TypedContractMethod<
    [_ubiPool: AddressLike, _treasury: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuthorizedCaller"
  ): TypedContractMethod<
    [caller: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ubiPool"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FeeRouted"
  ): TypedContractEvent<
    FeeRoutedEvent.InputTuple,
    FeeRoutedEvent.OutputTuple,
    FeeRoutedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "FeeRouted(bytes32,address,uint256,uint256,uint256)": TypedContractEvent<
      FeeRoutedEvent.InputTuple,
      FeeRoutedEvent.OutputTuple,
      FeeRoutedEvent.OutputObject
    >;
    FeeRouted: TypedContractEvent<
      FeeRoutedEvent.InputTuple,
      FeeRoutedEvent.OutputTuple,
      FeeRoutedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
