/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVeraScoreRegistry__factory } from "./IVeraScoreRegistry__factory";
export { VeraGigLendingPool__factory } from "./VeraGigLendingPool__factory";
