/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVeraGigFeeRouter } from "./IVeraGigFeeRouter";
export type { IVeraScoreRegistry } from "./IVeraScoreRegistry";
export type { VeraGigEscrow } from "./VeraGigEscrow";
