/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace VeraGigEscrow {
  export type TaskStruct = {
    id: BytesLike;
    client: AddressLike;
    worker: AddressLike;
    rewardWei: BigNumberish;
    deadline: BigNumberish;
    status: BigNumberish;
    deliverableCid: BytesLike;
    rating: BigNumberish;
    releaseAsStream: boolean;
    payoutDurationDays: BigNumberish;
  };

  export type TaskStructOutput = [
    id: string,
    client: string,
    worker: string,
    rewardWei: bigint,
    deadline: bigint,
    status: bigint,
    deliverableCid: string,
    rating: bigint,
    releaseAsStream: boolean,
    payoutDurationDays: bigint
  ] & {
    id: string;
    client: string;
    worker: string;
    rewardWei: bigint;
    deadline: bigint;
    status: bigint;
    deliverableCid: string;
    rating: bigint;
    releaseAsStream: boolean;
    payoutDurationDays: bigint;
  };
}

export interface VeraGigEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOM"
      | "FEE_BPS"
      | "approveAndRelease"
      | "assignTask"
      | "cancelTask"
      | "createTask"
      | "disputes"
      | "feeRouter"
      | "gDollar"
      | "getTask"
      | "owner"
      | "raiseDispute"
      | "renounceOwnership"
      | "resolveDispute"
      | "scoreRegistry"
      | "submitDeliverable"
      | "tasks"
      | "transferOwnership"
      | "updateContracts"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeRaised"
      | "DisputeResolved"
      | "OwnershipTransferred"
      | "TaskAssigned"
      | "TaskCancelled"
      | "TaskCompleted"
      | "TaskCreated"
      | "TaskSubmitted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BPS_DENOM", values?: undefined): string;
  encodeFunctionData(functionFragment: "FEE_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approveAndRelease",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignTask",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [BytesLike, BigNumberish, BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "disputes", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "feeRouter", values?: undefined): string;
  encodeFunctionData(functionFragment: "gDollar", values?: undefined): string;
  encodeFunctionData(functionFragment: "getTask", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scoreRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitDeliverable",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateContracts",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "BPS_DENOM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "FEE_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveAndRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assignTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeRouter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gDollar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scoreRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitDeliverable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContracts",
    data: BytesLike
  ): Result;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    raiser: AddressLike,
    disputeId: BytesLike
  ];
  export type OutputTuple = [taskId: string, raiser: string, disputeId: string];
  export interface OutputObject {
    taskId: string;
    raiser: string;
    disputeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [taskId: BytesLike, winner: AddressLike];
  export type OutputTuple = [taskId: string, winner: string];
  export interface OutputObject {
    taskId: string;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAssignedEvent {
  export type InputTuple = [taskId: BytesLike, worker: AddressLike];
  export type OutputTuple = [taskId: string, worker: string];
  export interface OutputObject {
    taskId: string;
    worker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [taskId: BytesLike];
  export type OutputTuple = [taskId: string];
  export interface OutputObject {
    taskId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    worker: AddressLike,
    rating: BigNumberish
  ];
  export type OutputTuple = [taskId: string, worker: string, rating: bigint];
  export interface OutputObject {
    taskId: string;
    worker: string;
    rating: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    client: AddressLike,
    rewardWei: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    client: string,
    rewardWei: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    taskId: string;
    client: string;
    rewardWei: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskSubmittedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    worker: AddressLike,
    deliverableCid: BytesLike
  ];
  export type OutputTuple = [
    taskId: string,
    worker: string,
    deliverableCid: string
  ];
  export interface OutputObject {
    taskId: string;
    worker: string;
    deliverableCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VeraGigEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): VeraGigEscrow;
  waitForDeployment(): Promise<this>;

  interface: VeraGigEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOM: TypedContractMethod<[], [bigint], "view">;

  FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  approveAndRelease: TypedContractMethod<
    [taskId: BytesLike, rating: BigNumberish],
    [void],
    "nonpayable"
  >;

  assignTask: TypedContractMethod<
    [taskId: BytesLike, worker: AddressLike],
    [void],
    "nonpayable"
  >;

  cancelTask: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  createTask: TypedContractMethod<
    [
      taskId: BytesLike,
      rewardWei: BigNumberish,
      deadline: BigNumberish,
      releaseAsStream: boolean,
      payoutDurationDays: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  disputes: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  feeRouter: TypedContractMethod<[], [string], "view">;

  gDollar: TypedContractMethod<[], [string], "view">;

  getTask: TypedContractMethod<
    [taskId: BytesLike],
    [VeraGigEscrow.TaskStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  raiseDispute: TypedContractMethod<
    [taskId: BytesLike, evidenceCid: BytesLike],
    [string],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [taskId: BytesLike, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  scoreRegistry: TypedContractMethod<[], [string], "view">;

  submitDeliverable: TypedContractMethod<
    [taskId: BytesLike, deliverableCid: BytesLike],
    [void],
    "nonpayable"
  >;

  tasks: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        boolean,
        bigint
      ] & {
        id: string;
        client: string;
        worker: string;
        rewardWei: bigint;
        deadline: bigint;
        status: bigint;
        deliverableCid: string;
        rating: bigint;
        releaseAsStream: boolean;
        payoutDurationDays: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateContracts: TypedContractMethod<
    [_scoreRegistry: AddressLike, _feeRouter: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveAndRelease"
  ): TypedContractMethod<
    [taskId: BytesLike, rating: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assignTask"
  ): TypedContractMethod<
    [taskId: BytesLike, worker: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [
      taskId: BytesLike,
      rewardWei: BigNumberish,
      deadline: BigNumberish,
      releaseAsStream: boolean,
      payoutDurationDays: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "feeRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gDollar"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [VeraGigEscrow.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<
    [taskId: BytesLike, evidenceCid: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [taskId: BytesLike, winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scoreRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitDeliverable"
  ): TypedContractMethod<
    [taskId: BytesLike, deliverableCid: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        boolean,
        bigint
      ] & {
        id: string;
        client: string;
        worker: string;
        rewardWei: bigint;
        deadline: bigint;
        status: bigint;
        deliverableCid: string;
        rating: bigint;
        releaseAsStream: boolean;
        payoutDurationDays: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateContracts"
  ): TypedContractMethod<
    [_scoreRegistry: AddressLike, _feeRouter: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TaskAssigned"
  ): TypedContractEvent<
    TaskAssignedEvent.InputTuple,
    TaskAssignedEvent.OutputTuple,
    TaskAssignedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskSubmitted"
  ): TypedContractEvent<
    TaskSubmittedEvent.InputTuple,
    TaskSubmittedEvent.OutputTuple,
    TaskSubmittedEvent.OutputObject
  >;

  filters: {
    "DisputeRaised(bytes32,address,bytes32)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(bytes32,address)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TaskAssigned(bytes32,address)": TypedContractEvent<
      TaskAssignedEvent.InputTuple,
      TaskAssignedEvent.OutputTuple,
      TaskAssignedEvent.OutputObject
    >;
    TaskAssigned: TypedContractEvent<
      TaskAssignedEvent.InputTuple,
      TaskAssignedEvent.OutputTuple,
      TaskAssignedEvent.OutputObject
    >;

    "TaskCancelled(bytes32)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskCompleted(bytes32,address,uint8)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;

    "TaskCreated(bytes32,address,uint256,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskSubmitted(bytes32,address,bytes32)": TypedContractEvent<
      TaskSubmittedEvent.InputTuple,
      TaskSubmittedEvent.OutputTuple,
      TaskSubmittedEvent.OutputObject
    >;
    TaskSubmitted: TypedContractEvent<
      TaskSubmittedEvent.InputTuple,
      TaskSubmittedEvent.OutputTuple,
      TaskSubmittedEvent.OutputObject
    >;
  };
}
