/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVeraScoreRegistry } from "./IVeraScoreRegistry";
export type { VeraGigLendingPool } from "./VeraGigLendingPool";
