/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace VeraGigLendingPool {
  export type LoanStruct = {
    id: BytesLike;
    worker: AddressLike;
    principalWei: BigNumberish;
    remainingWei: BigNumberish;
    repaymentDeductionPct: BigNumberish;
    createdAt: BigNumberish;
    fullyRepaid: boolean;
  };

  export type LoanStructOutput = [
    id: string,
    worker: string,
    principalWei: bigint,
    remainingWei: bigint,
    repaymentDeductionPct: bigint,
    createdAt: bigint,
    fullyRepaid: boolean
  ] & {
    id: string;
    worker: string;
    principalWei: bigint;
    remainingWei: bigint;
    repaymentDeductionPct: bigint;
    createdAt: bigint;
    fullyRepaid: boolean;
  };
}

export interface VeraGigLendingPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BUILDER_DEDUCTION"
      | "BUILDER_MAX"
      | "PRIME_DEDUCTION"
      | "PRIME_MAX"
      | "STARTER_DEDUCTION"
      | "STARTER_MAX"
      | "activeLoanId"
      | "authorizedRepayers"
      | "checkEligibility"
      | "deposit"
      | "gDollar"
      | "getLoan"
      | "loans"
      | "owner"
      | "processRepayment"
      | "renounceOwnership"
      | "requestLoan"
      | "scoreRegistry"
      | "setAuthorizedRepayer"
      | "totalPoolBalance"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LoanFullyRepaid"
      | "LoanIssued"
      | "LoanRepayment"
      | "OwnershipTransferred"
      | "PoolDeposit"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BUILDER_DEDUCTION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BUILDER_MAX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRIME_DEDUCTION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PRIME_MAX", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "STARTER_DEDUCTION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STARTER_MAX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeLoanId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedRepayers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkEligibility",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "gDollar", values?: undefined): string;
  encodeFunctionData(functionFragment: "getLoan", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "loans", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processRepayment",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestLoan",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "scoreRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedRepayer",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPoolBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BUILDER_DEDUCTION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BUILDER_MAX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRIME_DEDUCTION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRIME_MAX", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "STARTER_DEDUCTION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STARTER_MAX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeLoanId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedRepayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gDollar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processRepayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scoreRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedRepayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPoolBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace LoanFullyRepaidEvent {
  export type InputTuple = [loanId: BytesLike, worker: AddressLike];
  export type OutputTuple = [loanId: string, worker: string];
  export interface OutputObject {
    loanId: string;
    worker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanIssuedEvent {
  export type InputTuple = [
    loanId: BytesLike,
    worker: AddressLike,
    amountWei: BigNumberish
  ];
  export type OutputTuple = [loanId: string, worker: string, amountWei: bigint];
  export interface OutputObject {
    loanId: string;
    worker: string;
    amountWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaymentEvent {
  export type InputTuple = [
    loanId: BytesLike,
    deductionWei: BigNumberish,
    remainingWei: BigNumberish
  ];
  export type OutputTuple = [
    loanId: string,
    deductionWei: bigint,
    remainingWei: bigint
  ];
  export interface OutputObject {
    loanId: string;
    deductionWei: bigint;
    remainingWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolDepositEvent {
  export type InputTuple = [depositor: AddressLike, amountWei: BigNumberish];
  export type OutputTuple = [depositor: string, amountWei: bigint];
  export interface OutputObject {
    depositor: string;
    amountWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VeraGigLendingPool extends BaseContract {
  connect(runner?: ContractRunner | null): VeraGigLendingPool;
  waitForDeployment(): Promise<this>;

  interface: VeraGigLendingPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BUILDER_DEDUCTION: TypedContractMethod<[], [bigint], "view">;

  BUILDER_MAX: TypedContractMethod<[], [bigint], "view">;

  PRIME_DEDUCTION: TypedContractMethod<[], [bigint], "view">;

  PRIME_MAX: TypedContractMethod<[], [bigint], "view">;

  STARTER_DEDUCTION: TypedContractMethod<[], [bigint], "view">;

  STARTER_MAX: TypedContractMethod<[], [bigint], "view">;

  activeLoanId: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  authorizedRepayers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  checkEligibility: TypedContractMethod<
    [worker: AddressLike],
    [
      [boolean, bigint, bigint, string, string] & {
        isEligible: boolean;
        maxLoanWei: bigint;
        repaymentPct: bigint;
        tier: string;
        reason: string;
      }
    ],
    "view"
  >;

  deposit: TypedContractMethod<[amountWei: BigNumberish], [void], "nonpayable">;

  gDollar: TypedContractMethod<[], [string], "view">;

  getLoan: TypedContractMethod<
    [loanId: BytesLike],
    [VeraGigLendingPool.LoanStructOutput],
    "view"
  >;

  loans: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        id: string;
        worker: string;
        principalWei: bigint;
        remainingWei: bigint;
        repaymentDeductionPct: bigint;
        createdAt: bigint;
        fullyRepaid: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  processRepayment: TypedContractMethod<
    [loanId: BytesLike, payoutAmountWei: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestLoan: TypedContractMethod<
    [requestedWei: BigNumberish, purpose: string],
    [string],
    "nonpayable"
  >;

  scoreRegistry: TypedContractMethod<[], [string], "view">;

  setAuthorizedRepayer: TypedContractMethod<
    [repayer: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  totalPoolBalance: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BUILDER_DEDUCTION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BUILDER_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRIME_DEDUCTION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRIME_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STARTER_DEDUCTION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STARTER_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeLoanId"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "authorizedRepayers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkEligibility"
  ): TypedContractMethod<
    [worker: AddressLike],
    [
      [boolean, bigint, bigint, string, string] & {
        isEligible: boolean;
        maxLoanWei: bigint;
        repaymentPct: bigint;
        tier: string;
        reason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amountWei: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gDollar"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [loanId: BytesLike],
    [VeraGigLendingPool.LoanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        id: string;
        worker: string;
        principalWei: bigint;
        remainingWei: bigint;
        repaymentDeductionPct: bigint;
        createdAt: bigint;
        fullyRepaid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processRepayment"
  ): TypedContractMethod<
    [loanId: BytesLike, payoutAmountWei: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestLoan"
  ): TypedContractMethod<
    [requestedWei: BigNumberish, purpose: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scoreRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAuthorizedRepayer"
  ): TypedContractMethod<
    [repayer: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalPoolBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "LoanFullyRepaid"
  ): TypedContractEvent<
    LoanFullyRepaidEvent.InputTuple,
    LoanFullyRepaidEvent.OutputTuple,
    LoanFullyRepaidEvent.OutputObject
  >;
  getEvent(
    key: "LoanIssued"
  ): TypedContractEvent<
    LoanIssuedEvent.InputTuple,
    LoanIssuedEvent.OutputTuple,
    LoanIssuedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepayment"
  ): TypedContractEvent<
    LoanRepaymentEvent.InputTuple,
    LoanRepaymentEvent.OutputTuple,
    LoanRepaymentEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolDeposit"
  ): TypedContractEvent<
    PoolDepositEvent.InputTuple,
    PoolDepositEvent.OutputTuple,
    PoolDepositEvent.OutputObject
  >;

  filters: {
    "LoanFullyRepaid(bytes32,address)": TypedContractEvent<
      LoanFullyRepaidEvent.InputTuple,
      LoanFullyRepaidEvent.OutputTuple,
      LoanFullyRepaidEvent.OutputObject
    >;
    LoanFullyRepaid: TypedContractEvent<
      LoanFullyRepaidEvent.InputTuple,
      LoanFullyRepaidEvent.OutputTuple,
      LoanFullyRepaidEvent.OutputObject
    >;

    "LoanIssued(bytes32,address,uint256)": TypedContractEvent<
      LoanIssuedEvent.InputTuple,
      LoanIssuedEvent.OutputTuple,
      LoanIssuedEvent.OutputObject
    >;
    LoanIssued: TypedContractEvent<
      LoanIssuedEvent.InputTuple,
      LoanIssuedEvent.OutputTuple,
      LoanIssuedEvent.OutputObject
    >;

    "LoanRepayment(bytes32,uint256,uint256)": TypedContractEvent<
      LoanRepaymentEvent.InputTuple,
      LoanRepaymentEvent.OutputTuple,
      LoanRepaymentEvent.OutputObject
    >;
    LoanRepayment: TypedContractEvent<
      LoanRepaymentEvent.InputTuple,
      LoanRepaymentEvent.OutputTuple,
      LoanRepaymentEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolDeposit(address,uint256)": TypedContractEvent<
      PoolDepositEvent.InputTuple,
      PoolDepositEvent.OutputTuple,
      PoolDepositEvent.OutputObject
    >;
    PoolDeposit: TypedContractEvent<
      PoolDepositEvent.InputTuple,
      PoolDepositEvent.OutputTuple,
      PoolDepositEvent.OutputObject
    >;
  };
}
