/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVeraGigFeeRouter,
  IVeraGigFeeRouterInterface,
} from "../../../contracts/VeraGigEscrow.sol/IVeraGigFeeRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "taskId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "settlementAmount",
        type: "uint256",
      },
    ],
    name: "routeFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVeraGigFeeRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IVeraGigFeeRouterInterface {
    return new Interface(_abi) as IVeraGigFeeRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVeraGigFeeRouter {
    return new Contract(address, _abi, runner) as unknown as IVeraGigFeeRouter;
  }
}
