/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVeraScoreRegistry,
  IVeraScoreRegistryInterface,
} from "../../../contracts/VeraGigEscrow.sol/IVeraScoreRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "worker",
        type: "address",
      },
    ],
    name: "getScore",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "worker",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "newScore",
        type: "uint16",
      },
      {
        internalType: "uint32",
        name: "tasksCompleted",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "tasksAccepted",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "disputesLost",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "loansRepaidOnTime",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "ubiClaimStreakDays",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "earningConsistencyWeeks",
        type: "uint32",
      },
      {
        internalType: "string",
        name: "trigger",
        type: "string",
      },
    ],
    name: "updateScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVeraScoreRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IVeraScoreRegistryInterface {
    return new Interface(_abi) as IVeraScoreRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVeraScoreRegistry {
    return new Contract(address, _abi, runner) as unknown as IVeraScoreRegistry;
  }
}
